language: rust
matrix:
  include:
    - rust: nightly
      env: FEATURES='stm32f407'
    - rust: nightly
      env: FEATURES='stm32f417'
    - rust: nightly
      env: FEATURES='stm32f427'
    - rust: nightly
      env: FEATURES='stm32f429'
    - rust: nightly
      env: FEATURES='stm32f437'
    - rust: nightly
      env: FEATURES='stm32f439'
    - rust: nightly
      env: FEATURES='stm32f469'
    - rust: nightly
      env: FEATURES='stm32f479'
    - rust: nightly
      env: FEATURES='stm32f429' ARGS="--release --target=thumbv7em-none-eabihf --example=pktgen"
    - rust: nightly
      env: FEATURES='stm32f429 smoltcp-phy log smoltcp/socket-tcp smoltcp/socket-icmp smoltcp/log smoltcp/verbose' ARGS="--release --target=thumbv7em-none-eabihf --example=ip"
    - rust: nightly
      env: FEATURES='stm32f745'
    - rust: nightly
      env: FEATURES='stm32f746'
    - rust: nightly
      env: FEATURES='stm32f756'
    - rust: nightly
      env: FEATURES='stm32f765'
    - rust: nightly
      env: FEATURES='stm32f767'
    - rust: nightly
      env: FEATURES='stm32f769'
    - rust: nightly
      env: FEATURES='stm32f777'
    - rust: nightly
      env: FEATURES='stm32f778'
    - rust: nightly
      env: FEATURES='stm32f779'
      
script:
  - "cargo build --target=`uname -m`-unknown-linux-gnu --no-default-features --features \"$FEATURES\""
